name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            openjdk-17-jdk \
            autoconf \
            libtool \
            pkg-config \
            ccache
          pip install --upgrade pip "setuptools<69.0.0"
          pip install "cython<3.0.0" buildozer

      - name: Build with Buildozer
        env:
          ANDROID_NDK_HOME: ""
          ANDROID_NDK_ROOT: ""
          ANDROID_NDK: ""
        run: buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: stok-takip-apk
          path: bin/*.apk
